# Project information
site_name: Openpipe
site_description: A human friendly data-oriented integration toolkit
site_author: João Pinto
site_url: https://www.openpipe.org/
docs_dir: docs.in/

# Repository
repo_name: The Openpipe Tool
repo_url: https://github.com/Openpipe/openpipe/

# Repository
copyright: This site content is licensed under a <A HREF="https://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</A>

theme:
    name: material
    language: en
    palette:
        primary: 'blue'
        accent: 'green'

# Disable edit uri to get a cleaner view
edit_uri: ''

extra_css:
    - css/extra.css
    - https://cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.css

extra_javascript:
    - js/autoexpand.js
    - https://cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.js
    - js/consentinit.js

nav:
    - Home: index.md
    - Language: 1.0/language.md
    - Tool: 1.0/tool.md
    - Actions: 1.0/actions.md
    - Actions Development: 1.0/action-devel.md


markdown_extensions:
    - codehilite:   # This adds the "Copy to clipboard"
    - admonition:
    - pymdownx.details:
    - pymdownx.superfences:
