# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions

from .create_chat_completion_request_req_payload_tool_choice_function import (
    CreateChatCompletionRequestReqPayloadToolChoiceFunction,
)

CreateChatCompletionRequestReqPayloadToolChoice = typing.Union[
    typing_extensions.Literal["none"],
    typing_extensions.Literal["auto"],
    CreateChatCompletionRequestReqPayloadToolChoiceFunction,
]
