# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import typing_extensions

from .create_chat_completion_request_messages_item_assistant import CreateChatCompletionRequestMessagesItemAssistant
from .create_chat_completion_request_messages_item_function import CreateChatCompletionRequestMessagesItemFunction
from .create_chat_completion_request_messages_item_system import CreateChatCompletionRequestMessagesItemSystem
from .create_chat_completion_request_messages_item_tool import CreateChatCompletionRequestMessagesItemTool
from .create_chat_completion_request_messages_item_user import CreateChatCompletionRequestMessagesItemUser


class CreateChatCompletionRequestMessagesItem_System(CreateChatCompletionRequestMessagesItemSystem):
    role: typing_extensions.Literal["system"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class CreateChatCompletionRequestMessagesItem_User(CreateChatCompletionRequestMessagesItemUser):
    role: typing_extensions.Literal["user"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class CreateChatCompletionRequestMessagesItem_Assistant(CreateChatCompletionRequestMessagesItemAssistant):
    role: typing_extensions.Literal["assistant"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class CreateChatCompletionRequestMessagesItem_Tool(CreateChatCompletionRequestMessagesItemTool):
    role: typing_extensions.Literal["tool"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class CreateChatCompletionRequestMessagesItem_Function(CreateChatCompletionRequestMessagesItemFunction):
    role: typing_extensions.Literal["function"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


CreateChatCompletionRequestMessagesItem = typing.Union[
    CreateChatCompletionRequestMessagesItem_System,
    CreateChatCompletionRequestMessagesItem_User,
    CreateChatCompletionRequestMessagesItem_Assistant,
    CreateChatCompletionRequestMessagesItem_Tool,
    CreateChatCompletionRequestMessagesItem_Function,
]
