# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import typing_extensions

from .create_chat_completion_request_req_payload_messages_item_assistant import (
    CreateChatCompletionRequestReqPayloadMessagesItemAssistant,
)
from .create_chat_completion_request_req_payload_messages_item_function import (
    CreateChatCompletionRequestReqPayloadMessagesItemFunction,
)
from .create_chat_completion_request_req_payload_messages_item_system import (
    CreateChatCompletionRequestReqPayloadMessagesItemSystem,
)
from .create_chat_completion_request_req_payload_messages_item_tool import (
    CreateChatCompletionRequestReqPayloadMessagesItemTool,
)
from .create_chat_completion_request_req_payload_messages_item_user import (
    CreateChatCompletionRequestReqPayloadMessagesItemUser,
)


class CreateChatCompletionRequestReqPayloadMessagesItem_System(CreateChatCompletionRequestReqPayloadMessagesItemSystem):
    role: typing_extensions.Literal["system"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class CreateChatCompletionRequestReqPayloadMessagesItem_User(CreateChatCompletionRequestReqPayloadMessagesItemUser):
    role: typing_extensions.Literal["user"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class CreateChatCompletionRequestReqPayloadMessagesItem_Assistant(
    CreateChatCompletionRequestReqPayloadMessagesItemAssistant
):
    role: typing_extensions.Literal["assistant"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class CreateChatCompletionRequestReqPayloadMessagesItem_Tool(CreateChatCompletionRequestReqPayloadMessagesItemTool):
    role: typing_extensions.Literal["tool"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class CreateChatCompletionRequestReqPayloadMessagesItem_Function(
    CreateChatCompletionRequestReqPayloadMessagesItemFunction
):
    role: typing_extensions.Literal["function"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


CreateChatCompletionRequestReqPayloadMessagesItem = typing.Union[
    CreateChatCompletionRequestReqPayloadMessagesItem_System,
    CreateChatCompletionRequestReqPayloadMessagesItem_User,
    CreateChatCompletionRequestReqPayloadMessagesItem_Assistant,
    CreateChatCompletionRequestReqPayloadMessagesItem_Tool,
    CreateChatCompletionRequestReqPayloadMessagesItem_Function,
]
