# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions

CreateChatCompletionRequestMessagesItemFunctionContent = typing.Union[
    str, typing.Optional[typing_extensions.Literal["null"]]
]
