# This file was auto-generated by Fern from our API Definition.

import typing

from .create_chat_completion_request_messages_item_user_content_item import (
    CreateChatCompletionRequestMessagesItemUserContentItem,
)

CreateChatCompletionRequestMessagesItemUserContent = typing.Union[
    str, typing.List[CreateChatCompletionRequestMessagesItemUserContentItem]
]
