# This file was auto-generated by Fern from our API Definition.

import typing

from .create_chat_completion_response_choices import CreateChatCompletionResponseChoices

CreateChatCompletionResponse = typing.Union[typing.Optional[CreateChatCompletionResponseChoices], typing.Any]
