# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions

ReportRequestTagsValue = typing.Union[str, float, bool, typing.Optional[typing_extensions.Literal["null"]]]
