# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class UnstableFinetuneCreateRequestBaseModel(str, enum.Enum):
    OPEN_PIPE_MISTRAL_FT_OPTIMIZED_1227 = "OpenPipe/mistral-ft-optimized-1227"
    META_LLAMA_LLAMA_213_B_HF = "meta-llama/Llama-2-13b-hf"
    MISTRALAI_MIXTRAL_8_X_7_B_INSTRUCT_V_01 = "mistralai/Mixtral-8x7B-Instruct-v0.1"

    def visit(
        self,
        open_pipe_mistral_ft_optimized_1227: typing.Callable[[], T_Result],
        meta_llama_llama_213_b_hf: typing.Callable[[], T_Result],
        mistralai_mixtral_8_x_7_b_instruct_v_01: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is UnstableFinetuneCreateRequestBaseModel.OPEN_PIPE_MISTRAL_FT_OPTIMIZED_1227:
            return open_pipe_mistral_ft_optimized_1227()
        if self is UnstableFinetuneCreateRequestBaseModel.META_LLAMA_LLAMA_213_B_HF:
            return meta_llama_llama_213_b_hf()
        if self is UnstableFinetuneCreateRequestBaseModel.MISTRALAI_MIXTRAL_8_X_7_B_INSTRUCT_V_01:
            return mistralai_mixtral_8_x_7_b_instruct_v_01()
