# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import typing_extensions

from .create_chat_completion_request_req_payload_messages_item_user_content_item_image_url import (
    CreateChatCompletionRequestReqPayloadMessagesItemUserContentItemImageUrl,
)
from .create_chat_completion_request_req_payload_messages_item_user_content_item_text import (
    CreateChatCompletionRequestReqPayloadMessagesItemUserContentItemText,
)


class CreateChatCompletionRequestReqPayloadMessagesItemUserContentItem_ImageUrl(
    CreateChatCompletionRequestReqPayloadMessagesItemUserContentItemImageUrl
):
    type: typing_extensions.Literal["image_url"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class CreateChatCompletionRequestReqPayloadMessagesItemUserContentItem_Text(
    CreateChatCompletionRequestReqPayloadMessagesItemUserContentItemText
):
    type: typing_extensions.Literal["text"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


CreateChatCompletionRequestReqPayloadMessagesItemUserContentItem = typing.Union[
    CreateChatCompletionRequestReqPayloadMessagesItemUserContentItem_ImageUrl,
    CreateChatCompletionRequestReqPayloadMessagesItemUserContentItem_Text,
]
