# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class CreateChatCompletionRequestReqPayloadMessagesItemUserContentItemImageUrlImageUrlDetail(str, enum.Enum):
    AUTO = "auto"
    LOW = "low"
    HIGH = "high"

    def visit(
        self,
        auto: typing.Callable[[], T_Result],
        low: typing.Callable[[], T_Result],
        high: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is CreateChatCompletionRequestReqPayloadMessagesItemUserContentItemImageUrlImageUrlDetail.AUTO:
            return auto()
        if self is CreateChatCompletionRequestReqPayloadMessagesItemUserContentItemImageUrlImageUrlDetail.LOW:
            return low()
        if self is CreateChatCompletionRequestReqPayloadMessagesItemUserContentItemImageUrlImageUrlDetail.HIGH:
            return high()
