# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import typing_extensions

from .create_chat_completion_request_messages_item_user_content_item_image_url import (
    CreateChatCompletionRequestMessagesItemUserContentItemImageUrl,
)
from .create_chat_completion_request_messages_item_user_content_item_text import (
    CreateChatCompletionRequestMessagesItemUserContentItemText,
)


class CreateChatCompletionRequestMessagesItemUserContentItem_ImageUrl(
    CreateChatCompletionRequestMessagesItemUserContentItemImageUrl
):
    type: typing_extensions.Literal["image_url"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class CreateChatCompletionRequestMessagesItemUserContentItem_Text(
    CreateChatCompletionRequestMessagesItemUserContentItemText
):
    type: typing_extensions.Literal["text"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


CreateChatCompletionRequestMessagesItemUserContentItem = typing.Union[
    CreateChatCompletionRequestMessagesItemUserContentItem_ImageUrl,
    CreateChatCompletionRequestMessagesItemUserContentItem_Text,
]
