""" Contains all the data models used in inputs/outputs """

from .check_cache_json_body import CheckCacheJsonBody
from .check_cache_json_body_tags import CheckCacheJsonBodyTags
from .check_cache_response_200 import CheckCacheResponse200
from .create_chat_completion_json_body import CreateChatCompletionJsonBody
from .create_chat_completion_json_body_function_call_type_0 import CreateChatCompletionJsonBodyFunctionCallType0
from .create_chat_completion_json_body_function_call_type_1 import CreateChatCompletionJsonBodyFunctionCallType1
from .create_chat_completion_json_body_function_call_type_2 import CreateChatCompletionJsonBodyFunctionCallType2
from .create_chat_completion_json_body_functions_item import CreateChatCompletionJsonBodyFunctionsItem
from .create_chat_completion_json_body_functions_item_parameters import (
    CreateChatCompletionJsonBodyFunctionsItemParameters,
)
from .create_chat_completion_json_body_messages_item_type_0 import CreateChatCompletionJsonBodyMessagesItemType0
from .create_chat_completion_json_body_messages_item_type_0_content_type_1 import (
    CreateChatCompletionJsonBodyMessagesItemType0ContentType1,
)
from .create_chat_completion_json_body_messages_item_type_0_role import (
    CreateChatCompletionJsonBodyMessagesItemType0Role,
)
from .create_chat_completion_json_body_messages_item_type_1 import CreateChatCompletionJsonBodyMessagesItemType1
from .create_chat_completion_json_body_messages_item_type_1_content_type_1_item_type_0 import (
    CreateChatCompletionJsonBodyMessagesItemType1ContentType1ItemType0,
)
from .create_chat_completion_json_body_messages_item_type_1_content_type_1_item_type_0_image_url import (
    CreateChatCompletionJsonBodyMessagesItemType1ContentType1ItemType0ImageUrl,
)
from .create_chat_completion_json_body_messages_item_type_1_content_type_1_item_type_0_image_url_detail_type_0 import (
    CreateChatCompletionJsonBodyMessagesItemType1ContentType1ItemType0ImageUrlDetailType0,
)
from .create_chat_completion_json_body_messages_item_type_1_content_type_1_item_type_0_image_url_detail_type_1 import (
    CreateChatCompletionJsonBodyMessagesItemType1ContentType1ItemType0ImageUrlDetailType1,
)
from .create_chat_completion_json_body_messages_item_type_1_content_type_1_item_type_0_image_url_detail_type_2 import (
    CreateChatCompletionJsonBodyMessagesItemType1ContentType1ItemType0ImageUrlDetailType2,
)
from .create_chat_completion_json_body_messages_item_type_1_content_type_1_item_type_0_type import (
    CreateChatCompletionJsonBodyMessagesItemType1ContentType1ItemType0Type,
)
from .create_chat_completion_json_body_messages_item_type_1_content_type_1_item_type_1 import (
    CreateChatCompletionJsonBodyMessagesItemType1ContentType1ItemType1,
)
from .create_chat_completion_json_body_messages_item_type_1_content_type_1_item_type_1_type import (
    CreateChatCompletionJsonBodyMessagesItemType1ContentType1ItemType1Type,
)
from .create_chat_completion_json_body_messages_item_type_1_content_type_2 import (
    CreateChatCompletionJsonBodyMessagesItemType1ContentType2,
)
from .create_chat_completion_json_body_messages_item_type_1_role import (
    CreateChatCompletionJsonBodyMessagesItemType1Role,
)
from .create_chat_completion_json_body_messages_item_type_2 import CreateChatCompletionJsonBodyMessagesItemType2
from .create_chat_completion_json_body_messages_item_type_2_content_type_1 import (
    CreateChatCompletionJsonBodyMessagesItemType2ContentType1,
)
from .create_chat_completion_json_body_messages_item_type_2_function_call import (
    CreateChatCompletionJsonBodyMessagesItemType2FunctionCall,
)
from .create_chat_completion_json_body_messages_item_type_2_role import (
    CreateChatCompletionJsonBodyMessagesItemType2Role,
)
from .create_chat_completion_json_body_messages_item_type_2_tool_calls_item import (
    CreateChatCompletionJsonBodyMessagesItemType2ToolCallsItem,
)
from .create_chat_completion_json_body_messages_item_type_2_tool_calls_item_function import (
    CreateChatCompletionJsonBodyMessagesItemType2ToolCallsItemFunction,
)
from .create_chat_completion_json_body_messages_item_type_2_tool_calls_item_type import (
    CreateChatCompletionJsonBodyMessagesItemType2ToolCallsItemType,
)
from .create_chat_completion_json_body_messages_item_type_3 import CreateChatCompletionJsonBodyMessagesItemType3
from .create_chat_completion_json_body_messages_item_type_3_content_type_1 import (
    CreateChatCompletionJsonBodyMessagesItemType3ContentType1,
)
from .create_chat_completion_json_body_messages_item_type_3_role import (
    CreateChatCompletionJsonBodyMessagesItemType3Role,
)
from .create_chat_completion_json_body_messages_item_type_4 import CreateChatCompletionJsonBodyMessagesItemType4
from .create_chat_completion_json_body_messages_item_type_4_content_type_1 import (
    CreateChatCompletionJsonBodyMessagesItemType4ContentType1,
)
from .create_chat_completion_json_body_messages_item_type_4_role import (
    CreateChatCompletionJsonBodyMessagesItemType4Role,
)
from .create_chat_completion_json_body_req_payload import CreateChatCompletionJsonBodyReqPayload
from .create_chat_completion_json_body_req_payload_function_call_type_0 import (
    CreateChatCompletionJsonBodyReqPayloadFunctionCallType0,
)
from .create_chat_completion_json_body_req_payload_function_call_type_1 import (
    CreateChatCompletionJsonBodyReqPayloadFunctionCallType1,
)
from .create_chat_completion_json_body_req_payload_function_call_type_2 import (
    CreateChatCompletionJsonBodyReqPayloadFunctionCallType2,
)
from .create_chat_completion_json_body_req_payload_functions_item import (
    CreateChatCompletionJsonBodyReqPayloadFunctionsItem,
)
from .create_chat_completion_json_body_req_payload_functions_item_parameters import (
    CreateChatCompletionJsonBodyReqPayloadFunctionsItemParameters,
)
from .create_chat_completion_json_body_req_payload_messages_item_type_0 import (
    CreateChatCompletionJsonBodyReqPayloadMessagesItemType0,
)
from .create_chat_completion_json_body_req_payload_messages_item_type_0_content_type_1 import (
    CreateChatCompletionJsonBodyReqPayloadMessagesItemType0ContentType1,
)
from .create_chat_completion_json_body_req_payload_messages_item_type_0_role import (
    CreateChatCompletionJsonBodyReqPayloadMessagesItemType0Role,
)
from .create_chat_completion_json_body_req_payload_messages_item_type_1 import (
    CreateChatCompletionJsonBodyReqPayloadMessagesItemType1,
)
from .create_chat_completion_json_body_req_payload_messages_item_type_1_content_type_1_item_type_0 import (
    CreateChatCompletionJsonBodyReqPayloadMessagesItemType1ContentType1ItemType0,
)
from .create_chat_completion_json_body_req_payload_messages_item_type_1_content_type_1_item_type_0_image_url import (
    CreateChatCompletionJsonBodyReqPayloadMessagesItemType1ContentType1ItemType0ImageUrl,
)
from .create_chat_completion_json_body_req_payload_messages_item_type_1_content_type_1_item_type_0_image_url_detail_type_0 import (
    CreateChatCompletionJsonBodyReqPayloadMessagesItemType1ContentType1ItemType0ImageUrlDetailType0,
)
from .create_chat_completion_json_body_req_payload_messages_item_type_1_content_type_1_item_type_0_image_url_detail_type_1 import (
    CreateChatCompletionJsonBodyReqPayloadMessagesItemType1ContentType1ItemType0ImageUrlDetailType1,
)
from .create_chat_completion_json_body_req_payload_messages_item_type_1_content_type_1_item_type_0_image_url_detail_type_2 import (
    CreateChatCompletionJsonBodyReqPayloadMessagesItemType1ContentType1ItemType0ImageUrlDetailType2,
)
from .create_chat_completion_json_body_req_payload_messages_item_type_1_content_type_1_item_type_0_type import (
    CreateChatCompletionJsonBodyReqPayloadMessagesItemType1ContentType1ItemType0Type,
)
from .create_chat_completion_json_body_req_payload_messages_item_type_1_content_type_1_item_type_1 import (
    CreateChatCompletionJsonBodyReqPayloadMessagesItemType1ContentType1ItemType1,
)
from .create_chat_completion_json_body_req_payload_messages_item_type_1_content_type_1_item_type_1_type import (
    CreateChatCompletionJsonBodyReqPayloadMessagesItemType1ContentType1ItemType1Type,
)
from .create_chat_completion_json_body_req_payload_messages_item_type_1_content_type_2 import (
    CreateChatCompletionJsonBodyReqPayloadMessagesItemType1ContentType2,
)
from .create_chat_completion_json_body_req_payload_messages_item_type_1_role import (
    CreateChatCompletionJsonBodyReqPayloadMessagesItemType1Role,
)
from .create_chat_completion_json_body_req_payload_messages_item_type_2 import (
    CreateChatCompletionJsonBodyReqPayloadMessagesItemType2,
)
from .create_chat_completion_json_body_req_payload_messages_item_type_2_content_type_1 import (
    CreateChatCompletionJsonBodyReqPayloadMessagesItemType2ContentType1,
)
from .create_chat_completion_json_body_req_payload_messages_item_type_2_function_call import (
    CreateChatCompletionJsonBodyReqPayloadMessagesItemType2FunctionCall,
)
from .create_chat_completion_json_body_req_payload_messages_item_type_2_role import (
    CreateChatCompletionJsonBodyReqPayloadMessagesItemType2Role,
)
from .create_chat_completion_json_body_req_payload_messages_item_type_2_tool_calls_item import (
    CreateChatCompletionJsonBodyReqPayloadMessagesItemType2ToolCallsItem,
)
from .create_chat_completion_json_body_req_payload_messages_item_type_2_tool_calls_item_function import (
    CreateChatCompletionJsonBodyReqPayloadMessagesItemType2ToolCallsItemFunction,
)
from .create_chat_completion_json_body_req_payload_messages_item_type_2_tool_calls_item_type import (
    CreateChatCompletionJsonBodyReqPayloadMessagesItemType2ToolCallsItemType,
)
from .create_chat_completion_json_body_req_payload_messages_item_type_3 import (
    CreateChatCompletionJsonBodyReqPayloadMessagesItemType3,
)
from .create_chat_completion_json_body_req_payload_messages_item_type_3_content_type_1 import (
    CreateChatCompletionJsonBodyReqPayloadMessagesItemType3ContentType1,
)
from .create_chat_completion_json_body_req_payload_messages_item_type_3_role import (
    CreateChatCompletionJsonBodyReqPayloadMessagesItemType3Role,
)
from .create_chat_completion_json_body_req_payload_messages_item_type_4 import (
    CreateChatCompletionJsonBodyReqPayloadMessagesItemType4,
)
from .create_chat_completion_json_body_req_payload_messages_item_type_4_content_type_1 import (
    CreateChatCompletionJsonBodyReqPayloadMessagesItemType4ContentType1,
)
from .create_chat_completion_json_body_req_payload_messages_item_type_4_role import (
    CreateChatCompletionJsonBodyReqPayloadMessagesItemType4Role,
)
from .create_chat_completion_json_body_req_payload_response_format import (
    CreateChatCompletionJsonBodyReqPayloadResponseFormat,
)
from .create_chat_completion_json_body_req_payload_response_format_type_type_0 import (
    CreateChatCompletionJsonBodyReqPayloadResponseFormatTypeType0,
)
from .create_chat_completion_json_body_req_payload_response_format_type_type_1 import (
    CreateChatCompletionJsonBodyReqPayloadResponseFormatTypeType1,
)
from .create_chat_completion_json_body_req_payload_tool_choice_type_0 import (
    CreateChatCompletionJsonBodyReqPayloadToolChoiceType0,
)
from .create_chat_completion_json_body_req_payload_tool_choice_type_1 import (
    CreateChatCompletionJsonBodyReqPayloadToolChoiceType1,
)
from .create_chat_completion_json_body_req_payload_tool_choice_type_2 import (
    CreateChatCompletionJsonBodyReqPayloadToolChoiceType2,
)
from .create_chat_completion_json_body_req_payload_tool_choice_type_2_function import (
    CreateChatCompletionJsonBodyReqPayloadToolChoiceType2Function,
)
from .create_chat_completion_json_body_req_payload_tool_choice_type_2_type import (
    CreateChatCompletionJsonBodyReqPayloadToolChoiceType2Type,
)
from .create_chat_completion_json_body_req_payload_tools_item import CreateChatCompletionJsonBodyReqPayloadToolsItem
from .create_chat_completion_json_body_req_payload_tools_item_function import (
    CreateChatCompletionJsonBodyReqPayloadToolsItemFunction,
)
from .create_chat_completion_json_body_req_payload_tools_item_function_parameters import (
    CreateChatCompletionJsonBodyReqPayloadToolsItemFunctionParameters,
)
from .create_chat_completion_json_body_req_payload_tools_item_type import (
    CreateChatCompletionJsonBodyReqPayloadToolsItemType,
)
from .create_chat_completion_json_body_tool_choice_type_0 import CreateChatCompletionJsonBodyToolChoiceType0
from .create_chat_completion_json_body_tool_choice_type_1 import CreateChatCompletionJsonBodyToolChoiceType1
from .create_chat_completion_json_body_tool_choice_type_2 import CreateChatCompletionJsonBodyToolChoiceType2
from .create_chat_completion_json_body_tool_choice_type_2_function import (
    CreateChatCompletionJsonBodyToolChoiceType2Function,
)
from .create_chat_completion_json_body_tool_choice_type_2_type import CreateChatCompletionJsonBodyToolChoiceType2Type
from .create_chat_completion_json_body_tools_item import CreateChatCompletionJsonBodyToolsItem
from .create_chat_completion_json_body_tools_item_function import CreateChatCompletionJsonBodyToolsItemFunction
from .create_chat_completion_json_body_tools_item_function_parameters import (
    CreateChatCompletionJsonBodyToolsItemFunctionParameters,
)
from .create_chat_completion_json_body_tools_item_type import CreateChatCompletionJsonBodyToolsItemType
from .create_chat_completion_response_200 import CreateChatCompletionResponse200
from .create_chat_completion_response_200_choices_item import CreateChatCompletionResponse200ChoicesItem
from .create_chat_completion_response_200_choices_item_finish_reason_type_0 import (
    CreateChatCompletionResponse200ChoicesItemFinishReasonType0,
)
from .create_chat_completion_response_200_choices_item_finish_reason_type_1 import (
    CreateChatCompletionResponse200ChoicesItemFinishReasonType1,
)
from .create_chat_completion_response_200_choices_item_finish_reason_type_2 import (
    CreateChatCompletionResponse200ChoicesItemFinishReasonType2,
)
from .create_chat_completion_response_200_choices_item_finish_reason_type_3 import (
    CreateChatCompletionResponse200ChoicesItemFinishReasonType3,
)
from .create_chat_completion_response_200_choices_item_finish_reason_type_4 import (
    CreateChatCompletionResponse200ChoicesItemFinishReasonType4,
)
from .create_chat_completion_response_200_choices_item_message import CreateChatCompletionResponse200ChoicesItemMessage
from .create_chat_completion_response_200_choices_item_message_content_type_1 import (
    CreateChatCompletionResponse200ChoicesItemMessageContentType1,
)
from .create_chat_completion_response_200_choices_item_message_function_call import (
    CreateChatCompletionResponse200ChoicesItemMessageFunctionCall,
)
from .create_chat_completion_response_200_choices_item_message_role import (
    CreateChatCompletionResponse200ChoicesItemMessageRole,
)
from .create_chat_completion_response_200_choices_item_message_tool_calls_item import (
    CreateChatCompletionResponse200ChoicesItemMessageToolCallsItem,
)
from .create_chat_completion_response_200_choices_item_message_tool_calls_item_function import (
    CreateChatCompletionResponse200ChoicesItemMessageToolCallsItemFunction,
)
from .create_chat_completion_response_200_choices_item_message_tool_calls_item_type import (
    CreateChatCompletionResponse200ChoicesItemMessageToolCallsItemType,
)
from .create_chat_completion_response_200_object import CreateChatCompletionResponse200Object
from .create_chat_completion_response_200_usage import CreateChatCompletionResponse200Usage
from .local_testing_only_get_latest_logged_call_response_200 import LocalTestingOnlyGetLatestLoggedCallResponse200
from .local_testing_only_get_latest_logged_call_response_200_tags import (
    LocalTestingOnlyGetLatestLoggedCallResponse200Tags,
)
from .report_json_body import ReportJsonBody
from .report_json_body_tags import ReportJsonBodyTags
from .report_response_200 import ReportResponse200
from .report_response_200_status_type_0 import ReportResponse200StatusType0
from .report_response_200_status_type_1 import ReportResponse200StatusType1

__all__ = (
    "CheckCacheJsonBody",
    "CheckCacheJsonBodyTags",
    "CheckCacheResponse200",
    "CreateChatCompletionJsonBody",
    "CreateChatCompletionJsonBodyFunctionCallType0",
    "CreateChatCompletionJsonBodyFunctionCallType1",
    "CreateChatCompletionJsonBodyFunctionCallType2",
    "CreateChatCompletionJsonBodyFunctionsItem",
    "CreateChatCompletionJsonBodyFunctionsItemParameters",
    "CreateChatCompletionJsonBodyMessagesItemType0",
    "CreateChatCompletionJsonBodyMessagesItemType0ContentType1",
    "CreateChatCompletionJsonBodyMessagesItemType0Role",
    "CreateChatCompletionJsonBodyMessagesItemType1",
    "CreateChatCompletionJsonBodyMessagesItemType1ContentType1ItemType0",
    "CreateChatCompletionJsonBodyMessagesItemType1ContentType1ItemType0ImageUrl",
    "CreateChatCompletionJsonBodyMessagesItemType1ContentType1ItemType0ImageUrlDetailType0",
    "CreateChatCompletionJsonBodyMessagesItemType1ContentType1ItemType0ImageUrlDetailType1",
    "CreateChatCompletionJsonBodyMessagesItemType1ContentType1ItemType0ImageUrlDetailType2",
    "CreateChatCompletionJsonBodyMessagesItemType1ContentType1ItemType0Type",
    "CreateChatCompletionJsonBodyMessagesItemType1ContentType1ItemType1",
    "CreateChatCompletionJsonBodyMessagesItemType1ContentType1ItemType1Type",
    "CreateChatCompletionJsonBodyMessagesItemType1ContentType2",
    "CreateChatCompletionJsonBodyMessagesItemType1Role",
    "CreateChatCompletionJsonBodyMessagesItemType2",
    "CreateChatCompletionJsonBodyMessagesItemType2ContentType1",
    "CreateChatCompletionJsonBodyMessagesItemType2FunctionCall",
    "CreateChatCompletionJsonBodyMessagesItemType2Role",
    "CreateChatCompletionJsonBodyMessagesItemType2ToolCallsItem",
    "CreateChatCompletionJsonBodyMessagesItemType2ToolCallsItemFunction",
    "CreateChatCompletionJsonBodyMessagesItemType2ToolCallsItemType",
    "CreateChatCompletionJsonBodyMessagesItemType3",
    "CreateChatCompletionJsonBodyMessagesItemType3ContentType1",
    "CreateChatCompletionJsonBodyMessagesItemType3Role",
    "CreateChatCompletionJsonBodyMessagesItemType4",
    "CreateChatCompletionJsonBodyMessagesItemType4ContentType1",
    "CreateChatCompletionJsonBodyMessagesItemType4Role",
    "CreateChatCompletionJsonBodyReqPayload",
    "CreateChatCompletionJsonBodyReqPayloadFunctionCallType0",
    "CreateChatCompletionJsonBodyReqPayloadFunctionCallType1",
    "CreateChatCompletionJsonBodyReqPayloadFunctionCallType2",
    "CreateChatCompletionJsonBodyReqPayloadFunctionsItem",
    "CreateChatCompletionJsonBodyReqPayloadFunctionsItemParameters",
    "CreateChatCompletionJsonBodyReqPayloadMessagesItemType0",
    "CreateChatCompletionJsonBodyReqPayloadMessagesItemType0ContentType1",
    "CreateChatCompletionJsonBodyReqPayloadMessagesItemType0Role",
    "CreateChatCompletionJsonBodyReqPayloadMessagesItemType1",
    "CreateChatCompletionJsonBodyReqPayloadMessagesItemType1ContentType1ItemType0",
    "CreateChatCompletionJsonBodyReqPayloadMessagesItemType1ContentType1ItemType0ImageUrl",
    "CreateChatCompletionJsonBodyReqPayloadMessagesItemType1ContentType1ItemType0ImageUrlDetailType0",
    "CreateChatCompletionJsonBodyReqPayloadMessagesItemType1ContentType1ItemType0ImageUrlDetailType1",
    "CreateChatCompletionJsonBodyReqPayloadMessagesItemType1ContentType1ItemType0ImageUrlDetailType2",
    "CreateChatCompletionJsonBodyReqPayloadMessagesItemType1ContentType1ItemType0Type",
    "CreateChatCompletionJsonBodyReqPayloadMessagesItemType1ContentType1ItemType1",
    "CreateChatCompletionJsonBodyReqPayloadMessagesItemType1ContentType1ItemType1Type",
    "CreateChatCompletionJsonBodyReqPayloadMessagesItemType1ContentType2",
    "CreateChatCompletionJsonBodyReqPayloadMessagesItemType1Role",
    "CreateChatCompletionJsonBodyReqPayloadMessagesItemType2",
    "CreateChatCompletionJsonBodyReqPayloadMessagesItemType2ContentType1",
    "CreateChatCompletionJsonBodyReqPayloadMessagesItemType2FunctionCall",
    "CreateChatCompletionJsonBodyReqPayloadMessagesItemType2Role",
    "CreateChatCompletionJsonBodyReqPayloadMessagesItemType2ToolCallsItem",
    "CreateChatCompletionJsonBodyReqPayloadMessagesItemType2ToolCallsItemFunction",
    "CreateChatCompletionJsonBodyReqPayloadMessagesItemType2ToolCallsItemType",
    "CreateChatCompletionJsonBodyReqPayloadMessagesItemType3",
    "CreateChatCompletionJsonBodyReqPayloadMessagesItemType3ContentType1",
    "CreateChatCompletionJsonBodyReqPayloadMessagesItemType3Role",
    "CreateChatCompletionJsonBodyReqPayloadMessagesItemType4",
    "CreateChatCompletionJsonBodyReqPayloadMessagesItemType4ContentType1",
    "CreateChatCompletionJsonBodyReqPayloadMessagesItemType4Role",
    "CreateChatCompletionJsonBodyReqPayloadResponseFormat",
    "CreateChatCompletionJsonBodyReqPayloadResponseFormatTypeType0",
    "CreateChatCompletionJsonBodyReqPayloadResponseFormatTypeType1",
    "CreateChatCompletionJsonBodyReqPayloadToolChoiceType0",
    "CreateChatCompletionJsonBodyReqPayloadToolChoiceType1",
    "CreateChatCompletionJsonBodyReqPayloadToolChoiceType2",
    "CreateChatCompletionJsonBodyReqPayloadToolChoiceType2Function",
    "CreateChatCompletionJsonBodyReqPayloadToolChoiceType2Type",
    "CreateChatCompletionJsonBodyReqPayloadToolsItem",
    "CreateChatCompletionJsonBodyReqPayloadToolsItemFunction",
    "CreateChatCompletionJsonBodyReqPayloadToolsItemFunctionParameters",
    "CreateChatCompletionJsonBodyReqPayloadToolsItemType",
    "CreateChatCompletionJsonBodyToolChoiceType0",
    "CreateChatCompletionJsonBodyToolChoiceType1",
    "CreateChatCompletionJsonBodyToolChoiceType2",
    "CreateChatCompletionJsonBodyToolChoiceType2Function",
    "CreateChatCompletionJsonBodyToolChoiceType2Type",
    "CreateChatCompletionJsonBodyToolsItem",
    "CreateChatCompletionJsonBodyToolsItemFunction",
    "CreateChatCompletionJsonBodyToolsItemFunctionParameters",
    "CreateChatCompletionJsonBodyToolsItemType",
    "CreateChatCompletionResponse200",
    "CreateChatCompletionResponse200ChoicesItem",
    "CreateChatCompletionResponse200ChoicesItemFinishReasonType0",
    "CreateChatCompletionResponse200ChoicesItemFinishReasonType1",
    "CreateChatCompletionResponse200ChoicesItemFinishReasonType2",
    "CreateChatCompletionResponse200ChoicesItemFinishReasonType3",
    "CreateChatCompletionResponse200ChoicesItemFinishReasonType4",
    "CreateChatCompletionResponse200ChoicesItemMessage",
    "CreateChatCompletionResponse200ChoicesItemMessageContentType1",
    "CreateChatCompletionResponse200ChoicesItemMessageFunctionCall",
    "CreateChatCompletionResponse200ChoicesItemMessageRole",
    "CreateChatCompletionResponse200ChoicesItemMessageToolCallsItem",
    "CreateChatCompletionResponse200ChoicesItemMessageToolCallsItemFunction",
    "CreateChatCompletionResponse200ChoicesItemMessageToolCallsItemType",
    "CreateChatCompletionResponse200Object",
    "CreateChatCompletionResponse200Usage",
    "LocalTestingOnlyGetLatestLoggedCallResponse200",
    "LocalTestingOnlyGetLatestLoggedCallResponse200Tags",
    "ReportJsonBody",
    "ReportJsonBodyTags",
    "ReportResponse200",
    "ReportResponse200StatusType0",
    "ReportResponse200StatusType1",
)
